### PR TITLE
Add `var` from `{ a, b, c }@var` to scope

### PR DESCRIPTION
**Pull request by Ma27**
__Note:__ this is based on the `bump-rnix` branch and shouldn't be merged until that is merged to master.
cc @jD91mZM2

### CODE REVIEW

**Comment by jD91mZM2** [comment]
Thanks for noticing the `bump-rnix` branch, and basing it upon that! You're an absolute ninja :)

I'll try to get my things in order ASAP, I think what I'm missing is

1. a rowan release
2. https://github.com/nix-community/nixpkgs-fmt/pull/230 being merged + released

but I'll double check if that's absolutely necessary or not later

**Comment by Ma27** [comment]
AFAIU yes: I needed a newer `rnix-parser` (0.8.0 at least IIRC), but for that, a modified `nixpkgs-fmt` is needed. Tried that out first, but ran into issues with conflicting structs.

**Comment by Mic92** [comment]
The other PR was merged.

**Comment by jD91mZM2** [comment]
Alright, so it turns out naersk does not play well with `[patch.crates-io]` git dependencies. It's my bad, really, I shouldn't have reached out for `[patch.crates-io]` when we really did not need it. But instead of opening PRs to fix my mistake and polluting the git history, I'm taking the moment to ask for a release of rowan and then nixpkgs-fmt, so I can kill two birds with one stone and unlock the ability to release a new version of rnix-lsp (IIRC cargo doesn't allow git dependencies when releasing)

**Pull request merged**
