### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by Ma27**
This hopefully fixes the memory leak from https://github.com/nix-community/rnix-lsp/issues/33. Please refer to the commit messages for further details.

Please note that I only did some brief tests. I'd like to run this on my setup for a few days before merging this. Further testers are of course fairly welcome, so we can hopefully find out if my theory regarding #33 is correct :)

### CODE REVIEW

**Comment by Ma27** [comment]
Hmm, weird, `nix build -f . -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz -L` works fine locally. @Mic92 since you seen to have implemented this pipeline initially, do you have an idea what's up there? :)

**Comment by Mic92** [comment]
> Hmm, weird, `nix build -f . -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz -L` works fine locally. @Mic92 since you seen to have implemented this pipeline initially, do you have an idea what's up there? :)

`nixpkgs-channel` is no longer updated, try to switch `ttps://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz`

**Review by aaronjanse — APPROVED** [review]
Thank you @Ma27! This works well for me. I'm unable to reproduce the memory leak, so I don't know whether this PR fixes the issue, but I think it's good anyway to keep dependencies up-to-date.

Feel free to merge this if it has been working for you without issues :-)

**Comment by aaronjanse** [comment]
Maybe the memory leak is located in another dependency, such as `rowan`? There was a [rowan memory leak fix](https://github.com/rust-analyzer/rowan/pull/112) merged recently, but I doubt that something as severe as "uses all available memory" would silently be in something like rowan that's used by a lot of people

**Comment by Mic92** [comment]
Have you tried running one of the heap profilers out there, like heaptrack? 
I just found https://github.com/koute/bytehound I have not tested it though.

**Comment by Ma27** [comment]
>  I just found https://github.com/koute/bytehound I have not tested it though.

Thanks for the hint, not sure though how much it'll help if the leak is not properly reproducible, but it's definitely worth a shot.

Will try to resume my work on this leak-problem at one of the next days, going to merge this now since it appears to work fine :)

**Pull request merged**
