### PR TITLE
Use more modern flake definition based on updated naersk

### PR DESCRIPTION
**Pull request by antifuchs**
This PR eliminates the deprecated `edition` keyword, and lets naersk do all the work that the previous flake definition used to pull in several other repos in for (NUR and a utility repo mainly).

With this PR, I can run `nix run .` in the rnix-lsp checkout on latest unstable nix, and it's possible to use the flake in other flakes again.

### CODE REVIEW

**Comment by antifuchs** [comment]
Hm, correction: It seems the repo still can't be used as a dependent flake, as `default.nix` is still pulled in... Might be a bug in how I'm pulling it in, but it's suspicious. I'll investigate.

**Comment by zimbatm** [comment]
One thing I usually do is move all the project code into overlay.nix, and then initialize an instance of nixpkgs both in flake.nix and the default.nix using it. Then default.nix is only used as an entry point for nix-build and other old tooling.

**Comment by zimbatm** [comment]
One conflict here is that the third-party sources are managed both by flake and nix/sources.nix. Another way to do this is to not add any sources in flake.nix and reply solely on nix/sources.nix.

In order to make nix/sources.nix pure, first you have to mark the nixpkgs entry in nix/sources.json with the `"builtin": true` attribute so that it doesn't try to `import <nixpkgs> {}`.

**Comment by antifuchs** [comment]
Thanks for the suggestions, @zimbatm - I'm updating this PR status to Draft & will re-jigger parts in the hope that I can reflect your suggestions. 

I feel like usage via Flakes should cause the definition to not use niv, as users of the flake might grow accustomed to providing common dependencies if we have them in common via the `.follows` mechanism (as I had hoped to do). Marking things as `builtin` seems right though; I'll experiment a bit with this.

**Comment by jD91mZM2** [comment]
The `default.nix` should look like this:

```nix
(import (builtins.fetchTarball "https://github.com/edolstra/flake-compat/archive/master.tar.gz") {
  src = ./.;
}).defaultNix.default
```

That way we can get rid of having duplicate definitions of everything

**Comment by antifuchs** [comment]
Updated default.nix and shell.nix with @jD91mZM2's suggestion: As `nix/` (and niv) are redundant, I removed those files too.

This looks pretty tidy now, and I think this might be ready to review.

**Comment by jD91mZM2** [comment]
Those `import nixpkgs { inherit system; }` and `pkgs.callPackage naersk {}` are redundant, both flakes export usable attributes already. Here's some suggested cleanup, feel free to `git apply` if you agree with it:

```diff
diff --git a/flake.nix b/flake.nix
index e14dd63..778d2e0 100644
--- a/flake.nix
+++ b/flake.nix
@@ -1,23 +1,27 @@
 {
   description = "A work-in-progress language server for Nix, with syntax checking and basic completion";
 
-  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
-  inputs.naersk.url = "github:nmattia/naersk";
-  inputs.utils.url = "github:numtide/flake-utils";
+  inputs = {
+    naersk.url = "github:nmattia/naersk";
+    utils.url = "github:numtide/flake-utils";
+  };
 
   outputs = { self, nixpkgs, utils, naersk }:
     utils.lib.eachDefaultSystem (system:
       let
-        pkgs = import nixpkgs { inherit system; };
-        naersk-lib = pkgs.callPackage naersk { };
-      in
-      {
+        pkgs = nixpkgs.legacyPackages."${system}";
+        naersk-lib = naersk.lib."${system}";
+      in rec {
+        defaultPackage = (naersk-lib.buildPackage ./.) // {
+          pname = "rnix-lsp";
+        };
 
-        defaultPackage = naersk-lib.buildPackage ./.;
+        devShell = pkgs.mkShell {
+          nativeBuildInputs = with pkgs; [ rustc cargo ];
+        };
 
-        defaultApp = {
-          type = "app";
-          program = "${self.defaultPackage."${system}"}/bin/rnix-lsp";
+        defaultApp = utils.lib.mkApp {
+          drv = defaultPackage;
         };
       });
 }
```

**Review by jD91mZM2 — CHANGES_REQUESTED** [review]
​

**Comment by jD91mZM2** [comment]
Merged it and applied my changes early to fix #15. Sorry for the rush.

**Comment by antifuchs** [comment]
Ooh, thanks for merging & for the suggestions! I'm sorry I couldn't get your changes in earlier, but looks like you fixed it after all.

**Pull request merged**
