### PR TITLE
Add installation instructions

### PR DESCRIPTION
**Pull request by lf-**

### CODE REVIEW

**Comment by jD91mZM2** [comment]
You can already do that in one command:

```sh
nix-env -f <url> rnix-lsp
```

**Comment by lf-** [comment]
you can?! I am clearly experiencing an instance of Cunningham's law! Cool.

https://meta.wikimedia.org/wiki/Cunningham%27s_Law

**Comment by jD91mZM2** [comment]
The command I was looking for was `nix-env -f https://github.com/nix-community/rnix-lsp/archive/master.tar.gz -i`, it would appear

**Comment by lf-** [comment]
@jD91mZM2 Changed it as suggested :)

**Pull request merged**
